name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 18:30 UTC / 00:00 IST
    - cron: '30 18 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: joe733/waka-readme@workshop
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SHOW_TOTAL: true
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
